"""DEPRECATED — superseded by the monitor engine.

The descriptive hike/cut/hold action tracker is now the `action` column produced by
`python -m cbp.monitor`, and the hand-maintained meeting-date list lives in
`data/monitor/fomc_calendar.csv` (generated by scripts/seed_calendar.py). Run:

    python -m cbp.monitor                # score new statements + rebuild the dashboard
    python -m cbp.monitor --rebuild-only # re-render only (the CI path)

This shim is kept so old references fail loudly instead of running stale logic.
"""
import sys

if __name__ == "__main__":
    sys.exit("action_tone_monitor.py is deprecated — use `python -m cbp.monitor` (see module docstring).")
